version: "3"
services:
  pg:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
  pgadmin:
    image: dpage/pgadmin4:8.5
    ports:
      - "5050:80"
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - pg
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgadmin4/pgpass
  redis:
    image: redis/redis-stack:latest
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
      - "8001:8001"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - pg
      - redis

volumes:
  redis:
  postgres:
